[tool.poetry]
name = "opp"
version = "0.1.0"
description = "Keyboard eavesdropping"
authors = ["Rami && Bachir"]
package-mode = false
license = "MIT"

[tool.poetry.dependencies]
python = "^3.13"
taskipy = "^1.14.1"
pydantic = "^2.11.2"
pydantic-settings = "^2.8.1"
fastapi = {extras = ["standard"], version = "^0.115.12"}
matplotlib = "^3.10.1"
scipy = "^1.15.2"
sounddevice = "^0.5.1"
numpy = "^2.2.4"
pandas = "^2.2.3"
fastapi-utils = "^0.8.0"
requests = "^2.32.3"
httpcore = "^1.0.8"
httpx = "^0.28.1"
supabase = "^2.15.0"
celery = "^5.5.2"
redis = "^5.0.7"

[tool.poetry.group.dev.dependencies]
colorlog = "^6.9.0"
coverage = "^7.8.0"
pytest = "^8.3.5"
python-dotenv = "^1.1.0"
pre-commit = "^4.2.0"
black = "^25.1.0"
flower = "^2.0.1"

[tool.taskipy.tasks]
test = "coverage run -m pytest tests/"
report = "coverage report"
lint = "pre-commit run --all-files"
api = "python -m app"
supabase = "supabase start"
celery = "celery -A app.worker.celery worker --loglevel=info"
flower = "celery -A app.worker.celery flower --port=5555"

[tool.black]
line-length = 180
skip-string-normalization = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
