name: Test

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v26

      - name: Set up cache
        uses: cachix/cachix-action@v14
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Extract supabase service key
        run: |
          cp .env.example .env.test
          devenv shell supabase_extract_key

      - name: Run tests
        run: |
          set -a
          source .env.test
          set +a
          devenv test
